attr:
  - 速度
  - 攻击力
  - 防御力
  - 生命值
  - 暴击率
  - 暴击伤害
  - 击破特攻
  - 效果抵抗
  - 效果命中
  - 治疗量加成
  - 能量恢复效率
  - 冰属性伤害提高
  - 风属性伤害提高
  - 火属性伤害提高
  - 雷属性伤害提高
  - 量子属性伤害提高
  - 物理属性伤害提高
  - 虚数属性伤害提高
suit:
  - 云无留迹的过客
  - 野穗伴行的快枪手
  - 净庭教宗的圣骑士
  - 密林卧雪的猎人
  - 街头出身的拳王
  - 戍卫风雪的铁卫
  - 熔岩锻铸的火匠
  - 繁星璀璨的天才
  - 激奏雷电的乐队
  - 晨昏交界的翔鹰
  - 流星追迹的怪盗
  - 盗匪荒漠的废土客
  - 太空封印站
  - 不老者的仙舟
  - 泛银河商业公司
  - 筑城者的贝洛伯格
  - 星体差分机
  - 停转的萨尔索图
  - 盗贼公国塔利亚
  - 生命的翁瓦克
  - 繁星竞技场
  - 折断的龙骨
  - 宝命长存的莳者
  - 骇域漫游的信使
position:
  - 头部
  - 手部
  - 躯干
  - 脚部
  - 位面球
  - 连结绳
value: 
  - "0"
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "."
  - "+"
  - "%"